### Problem Statement

#### Objectives
A leading agri-tech company, AgroTech Innovations, faces significant challenges in optimising crop yields
and resource management due to inefficiencies in their controlled environment farming systems.
Despite having advanced sensor technologies, the company seeks to enhance its operational efficiency
and support future research and development initiatives.  

As a machine learning engineer at AgroTech Innovations, you are tasked with developing machine
learning models to address these challenges. Your goal is to create models to predict the temperature
conditions within the farm's closed environment, ensuring optimal plant growth. Additionally, you will
develop models to categorise the combined "Plant Type-Stage" based on sensor data, aiding in
strategic planning and resource allocation.  

By implementing these models, you will help AgroTech Innovations improve crop management,
optimise resource usage, and increase yield predictability. These efforts will not only enhance current
operations but also provide valuable insights for future agricultural innovations.  

In your submission, you are expected to evaluate at least two suitable models for each task and justify
your choices based on the dataset provided.

#### Dataset
The dataset contains sensor readings and plant-related information collected from various agricultural
zones within a controlled environment. It includes features such as temperature, humidity, light intensity,
CO2 levels, and nutrient concentrations. Note that the dataset may contain synthetic data. Therefore, you
would need to state any assumptions you make.  
    
You can query the datasets using the following URL:  
https://techassessment.blob.core.windows.net/aiap19-assessment-data/agri.db

### Libraries / Dependencies

In [1]:
## Import Libraries / Dependencies
# Data handling and graphics
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as stats

# Analysis and Transformers
from scipy.stats import ttest_ind, ks_2samp, chi2_contingency, levene, pearsonr
from sklearn.feature_selection import mutual_info_classif ,mutual_info_regression

### Data Ingestion

In [2]:
# Connect to thedatabase
db_path = 'data/agri.db'
conn = sqlite3.connect(db_path)

def database_audit(conn):
    # --- HEADER FORENSICS (Without struct) ---
    # We read the raw bytes to find the "Fingerprint" markers
    with open(db_path, 'rb') as f:
        # File Change Counter is 4 bytes at offset 24
        f.seek(24)
        change_counter = int.from_bytes(f.read(4), byteorder='big')
        
        # Application ID is 4 bytes at offset 68
        f.seek(68)
        app_id = int.from_bytes(f.read(4), byteorder='big')
        
    print("=== 1. GLOBAL SECURITY & INTEGRITY FLAGS ===")
    fk_enforced = conn.execute("PRAGMA foreign_keys;").fetchone()[0]
    writable = conn.execute("PRAGMA writable_schema;").fetchone()[0]
    schema_ver = conn.execute("PRAGMA schema_version;").fetchone()[0]
    integrity = conn.execute("PRAGMA integrity_check;").fetchone()[0]
    free_pages = conn.execute("PRAGMA freelist_count;").fetchone()[0]
    
    print(f"Foreign Key Enforcement: {'ACTIVE' if fk_enforced else 'DISABLED'}")
    print(f"Writable Schema (Risk):  {'DANGEROUS' if writable else 'SECURE'}")
    print(f"Schema Version:          {schema_ver}")
    print(f"File Change Counter:     {change_counter}")
    print(f"Application ID:          {app_id}")
    print(f"Freelist (Deleted Data): {free_pages} pages")
    print(f"Physical Integrity:      {integrity}")
    print("-" * 45)

    # 2. Get all objects including tables, views, and triggers
    objects = pd.read_sql_query("SELECT type, name, sql FROM sqlite_master;", conn)
    
    print("\n=== 2. TABLE-LEVEL AUDIT (STRICTNESS & HIDDEN COLS) ===")
    for _, row in objects[objects['type'] == 'table'].iterrows():
        table_name = row['name']
        sql_statement = row['sql'] if row['sql'] else ""
        
        # Check for the STRICT keyword in the SQL definition
        is_strict = "STRICT" in sql_statement.upper()
        
        print(f"\nTABLE: {table_name}")
        print(f"Strict Mode: {'ENABLED' if is_strict else 'DISABLED (Legacy Affinity)'}")
        
        # Using table_xinfo to catch hidden/system columns
        cols = pd.read_sql_query(f"PRAGMA table_xinfo('{table_name}');", conn)
        display(cols)

    # 3. Check for Triggers (Secret tampering logic)
    triggers = objects[objects['type'] == 'trigger']
    if not triggers.empty:
        print("\n=== 3. ACTIVE TRIGGERS (Automated Data Modification) ===")
        display(triggers[['name', 'sql']])
    else:
        print("\n=== 3. NO HIDDEN TRIGGERS FOUND ===")

    # 4. Check for Sequences (Auto-increment tracking)
    print("\n=== 4. SEQUENCE AUDIT (ID High-Water Marks) ===")
    # We check if sqlite_sequence exists in sqlite_master first
    check_seq_table = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='sqlite_sequence';"
    ).fetchone()

    if check_seq_table:
        # 'name' here is the table name, 'seq' is the last used ID (the Value)
        sequences = pd.read_sql_query("SELECT name AS 'Table', seq AS 'Last ID' FROM sqlite_sequence;", conn)
        print("The following tables use AUTOINCREMENT to prevent ID reuse:")
        display(sequences)
    else:
        print("No AUTOINCREMENT sequences defined in this database.")

    # 5. Others
    print("\n=== 5. Other Indicators ===")
    # Check for the hidden "History" stats table
    try:
        stats = pd.read_sql_query("SELECT * FROM sqlite_stat1;", conn)
        print("Optimization Stats Found (Historical Data Clues!)")
        display(stats)
    except:
        print("No historical stats found.")

    # Check the physical 'Age' via Page Size
    page_size = conn.execute("PRAGMA page_size;").fetchone()[0]
    encoding = conn.execute("PRAGMA encoding;").fetchone()[0]
    print(f"Page Size: {page_size} | Encoding: {encoding}")

database_audit(conn)
conn.close()

=== 1. GLOBAL SECURITY & INTEGRITY FLAGS ===
Foreign Key Enforcement: DISABLED
Writable Schema (Risk):  SECURE
Schema Version:          1
File Change Counter:     2
Application ID:          0
Freelist (Deleted Data): 0 pages
Physical Integrity:      ok
---------------------------------------------

=== 2. TABLE-LEVEL AUDIT (STRICTNESS & HIDDEN COLS) ===

TABLE: farm_data
Strict Mode: DISABLED (Legacy Affinity)

    cid                          name     type  notnull dflt_value  pk  hidden
0     0          System Location Code     TEXT        0       None   0       0
1     1     Previous Cycle Plant Type     TEXT        0       None   0       0
2     2                    Plant Type     TEXT        0       None   0       0
3     3                   Plant Stage     TEXT        0       None   0       0
4     4       Temperature Sensor (°C)     REAL        0       None   0       0
5     5           Humidity Sensor (%)     REAL        0       None   0       0
6     6  Light Intensity Sensor (lux)     REAL        0       None   0       0
7     7              CO2 Sensor (ppm)  INTEGER        0       None   0       0
8     8              EC Sensor (dS/m)     REAL        0       None   0       0
9     9               O2 Sensor (ppm)  INTEGER        0       None   0       0
10   10       Nutrient N Sensor (ppm)     TEXT        0       None   0       0
11   11       Nutrient P Sensor (ppm)     TEXT        0       None   0       0
12   12       Nutrient K Sensor (ppm)     TEXT        0       None   0       0
13   13                     pH Sensor     REAL        0       None   0       0
14   14       Water Level Sensor (mm)     REAL        0       None   0       0

=== 3. NO HIDDEN TRIGGERS FOUND ===

=== 4. SEQUENCE AUDIT (ID High-Water Marks) ===
No AUTOINCREMENT sequences defined in this database.

=== 5. Other Indicators ===
No historical stats found.
Page Size: 4096 | Encoding: UTF-8

#### Metadata Analysis
There are nothing particularly abnormal about the database itself.  
Howerer there is a lack of autoincrement meaning there possible scenarios that rows can be duplicated.  
The schema version 1 suggests that the data base has never been changed since creation.  
However there isnt a way to see if this is a snapshot or fork of a bigger database.

In [3]:
# Querying the table
conn = sqlite3.connect(db_path)
query = f"SELECT * FROM farm_data"
df_raw = pd.read_sql_query(query, conn, dtype_backend="pyarrow")
conn.close()
df_raw.head(10)

,System Location Code,Previous Cycle Plant Type,Plant Type,Plant Stage,Temperature Sensor (°C),Humidity Sensor (%),Light Intensity Sensor (lux),CO2 Sensor (ppm),EC Sensor (dS/m),O2 Sensor (ppm),Nutrient N Sensor (ppm),Nutrient P Sensor (ppm),Nutrient K Sensor (ppm),pH Sensor,Water Level Sensor (mm)
0,Zone_D,Herbs,Vine Crops,Maturity,23.34,<NA>,454.0,937,1.82,4,161,64,201,6.1,28.150346
1,Zone_G,Herbs,VINE CROPS,Vegetative,-24.16,63.14,441.0,938,2.13,6,161,53,<NA>,6.5,31.0
2,Zone_F,Herbs,herbs,maturity,23.84,<NA>,562.0,1246,1.21,8,228,79,292,6.4,26.0
3,Zone_G,Herbs,fruiting vegetables,Vegetative,22.61,<NA>,651.0,1346,1.96,6,<NA>,53 ppm,289,6.6,<NA>
4,Zone_B,Vine Crops,LEAFY GREENS,seedling,22.88,<NA>,144.0,812,2.76,5,61,19,168,5.5,28.0
5,Zone_C,Vine Crops,FRUITING VEGETABLES,MATURITY,25.96,<NA>,675.0,1338,1.75,8,227,53,258,6.2,23.092135
6,Zone_A,Leafy Greens,Vine Crops,Maturity,<NA>,<NA>,514.0,1103,1.14,8,174,62,217,5.5,35.0
7,Zone_G,Herbs,Leafy Greens,Maturity,20.16,<NA>,317.0,1133,1.52,10,<NA>,<NA>,277,5.8,39.611156
8,Zone_G,Herbs,Leafy Greens,Maturity,20.16,<NA>,317.0,1133,1.52,10,<NA>,<NA>,277,5.8,39.611156
9,Zone_B,Vine Crops,Vine Crops,MATURITY,25.59,<NA>,435.0,845,2.07,8,150,70,210,5.3,27.835062

In [4]:
# it is good practice to leave raw data untouched, so make a copy for analysis and revision
# convert_dtypes() convert columns from numpy dtypes to the best dtypes that support pd.NA. 
# In this case its just to cast dtypes so i know what needs cleaning
df_data = df_raw.copy().convert_dtypes()

There is a possibility that there is signal within the casing, whitespace, underscores and periods. But on a cursory glance i don't see any,  
And im not willing to spend time digging unless there are signs suggesting so.

In [5]:
# Basic cleaning of strings
for col in df_data.select_dtypes(include=['object', 'string']):
        df_data[col] = (
            df_data[col]
            .str.lower()                            # Converts text to lowercase
            .str.strip()                            # Strip leading/trailing whitespace
            .str.replace(r'\s+', '', regex=True)    # Remove all whitespace (including between words)
            .str.replace('_', '', regex=False)      # Remove all underscores
            .str.replace('.', '', regex=False)      # Remove all periods
        )

In [6]:
# Quick examination of the data
df_data.nunique()

System Location Code                7
Previous Cycle Plant Type           4
Plant Type                          4
Plant Stage                         3
Temperature Sensor (°C)          1439
Humidity Sensor (%)              2094
Light Intensity Sensor (lux)     1228
CO2 Sensor (ppm)                  702
EC Sensor (dS/m)                  336
O2 Sensor (ppm)                     9
Nutrient N Sensor (ppm)           322
Nutrient P Sensor (ppm)           118
Nutrient K Sensor (ppm)           395
pH Sensor                          39
Water Level Sensor (mm)         10832
dtype: int64

In [7]:
# Quick examination of null values and dtypes
df_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 57489 entries, 0 to 57488
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   System Location Code          57489 non-null  string
 1   Previous Cycle Plant Type     57489 non-null  string
 2   Plant Type                    57489 non-null  string
 3   Plant Stage                   57489 non-null  string
 4   Temperature Sensor (°C)       48800 non-null  Float64
 5   Humidity Sensor (%)           18622 non-null  Float64
 6   Light Intensity Sensor (lux)  53211 non-null  Float64
 7   CO2 Sensor (ppm)              57489 non-null  Int64
 8   EC Sensor (dS/m)              57489 non-null  Float64
 9   O2 Sensor (ppm)               57489 non-null  Int64
 10  Nutrient N Sensor (ppm)       47515 non-null  string
 11  Nutrient P Sensor (ppm)       51791 non-null  string
 12  Nutrient K Sensor (ppm)       53788 non-null  string
 13  pH Sensor                     57489 non-null  Float64
 14  Water Level Sensor (mm)       48847 non-null  Float64
dtypes: Float64(6), Int64(2), string(7)
memory usage: 9.4 MB

In [8]:
# Quick Check of duplicates
df_data[df_data.duplicated(keep=False)].head(30)

,System Location Code,Previous Cycle Plant Type,Plant Type,Plant Stage,Temperature Sensor (°C),Humidity Sensor (%),Light Intensity Sensor (lux),CO2 Sensor (ppm),EC Sensor (dS/m),O2 Sensor (ppm),Nutrient N Sensor (ppm),Nutrient P Sensor (ppm),Nutrient K Sensor (ppm),pH Sensor,Water Level Sensor (mm)
7,zoneg,herbs,leafygreens,maturity,20.16,<NA>,317.0,1133,1.52,10,<NA>,<NA>,277,5.8,39.611156
8,zoneg,herbs,leafygreens,maturity,20.16,<NA>,317.0,1133,1.52,10,<NA>,<NA>,277,5.8,39.611156
14,zoneb,herbs,fruitingvegetables,maturity,24.5,<NA>,664.0,1438,2.22,7,238,72,251,6.3,22.530938
15,zoneb,herbs,fruitingvegetables,maturity,24.5,<NA>,664.0,1438,2.22,7,238,72,251,6.3,22.530938
28,zonec,leafygreens,leafygreens,vegetative,21.88,65.62,387.0,1007,0.86,5,115,32,<NA>,6.3,20.0
29,zonec,leafygreens,leafygreens,vegetative,21.88,65.62,387.0,1007,0.86,5,115,32,<NA>,6.3,20.0
36,zoneb,vinecrops,leafygreens,seedling,22.27,<NA>,-105.0,901,1.83,6,93,23,189,6.2,29.0
37,zoneb,vinecrops,leafygreens,seedling,22.27,<NA>,-105.0,901,1.83,6,93,23,189,6.2,29.0
39,zonef,herbs,herbs,vegetative,23.09,<NA>,600.0,1156,1.07,8,238,74,308,6.4,<NA>
40,zonef,herbs,herbs,vegetative,23.09,<NA>,600.0,1156,1.07,8,238,74,308,6.4,<NA>
51,zonef,vinecrops,fruitingvegetables,vegetative,-22.96,<NA>,626.0,1096,1.83,6,<NA>,55,275,6.5,27.0
52,zonef,vinecrops,fruitingvegetables,vegetative,-22.96,<NA>,626.0,1096,1.83,6,<NA>,55,275,6.5,27.0
57,zonec,fruitingvegetables,herbs,maturity,24.0,<NA>,574.0,1251,1.45,5,221,54,261,6.5,21.0
58,zonec,fruitingvegetables,herbs,maturity,24.0,<NA>,574.0,1251,1.45,5,221,54,261,6.5,21.0
61,zonee,vinecrops,fruitingvegetables,seedling,<NA>,<NA>,595.0,1148,2.44,7,123,46,185,6.8,25.0
62,zonee,vinecrops,fruitingvegetables,seedling,<NA>,<NA>,595.0,1148,2.44,7,123,46,185,6.8,25.0
84,zonef,leafygreens,herbs,vegetative,23.72,66.38,483.0,1220,1.7,6,175,66,256,6.1,39.881748
85,zonef,leafygreens,herbs,vegetative,23.72,66.38,483.0,1220,1.7,6,175,66,256,6.1,39.881748
90,zonec,vinecrops,vinecrops,maturity,25.72,75.6,482.0,1083,1.79,9,183,50,200,5.2,14.207275
91,zonec,vinecrops,vinecrops,maturity,25.72,75.6,482.0,1083,1.79,9,183,50,200,5.2,14.207275
95,zonef,vinecrops,fruitingvegetables,vegetative,22.58,<NA>,672.0,1382,0.97,7,179,51,229,6.5,24.0
96,zonef,vinecrops,fruitingvegetables,vegetative,22.58,<NA>,672.0,1382,0.97,7,179,51,229,6.5,24.0
103,zoneg,leafygreens,vinecrops,seedling,<NA>,<NA>,240.0,993,2.39,5,120,30,139,5.6,20.0
104,zoneg,leafygreens,vinecrops,seedling,<NA>,<NA>,240.0,993,2.39,5,120,30,139,5.6,20.0
117,zonef,herbs,fruitingvegetables,seedling,24.99,<NA>,476.0,1021,0.84,7,144,46,157,5.9,<NA>
118,zonef,herbs,fruitingvegetables,seedling,24.99,<NA>,476.0,1021,0.84,7,144,46,157,5.9,<NA>
119,zonee,herbs,leafygreens,seedling,22.63,<NA>,107.0,885,1.16,4,78,23,126,6.0,23.0
120,zonee,herbs,leafygreens,seedling,22.63,<NA>,107.0,885,1.16,4,78,23,126,6.0,23.0
153,zonee,herbs,leafygreens,vegetative,20.45,60.99,228.0,1080,1.99,5,<NA>,33,259,5.4,20.0
154,zonee,herbs,leafygreens,vegetative,20.45,60.99,228.0,1080,1.99,5,<NA>,33,259,5.4,20.0

### Data Cleaning and Investigations

Cleaning is done in no particular order  
The Question of data storage is not explicitly stated and im reluctant to store cleaned data in .feather files where i have a .db to work with  

Presuming the database is the primary method of storage of the raw data  
Primary goal is to create a view in the SQL database through SQL 
As python is the requirement the current objective will be to do this in .py files using sqlite3  

Further considerations should be annotated for cleaning scripts in SQL for a smoother pipeline.

#### Handling duplicates and Index analysis

The duplicates are clustered together suggesting an input error.  
There is also signs that the index is an indicator of time series as most of the zone, previous plant type, plant type and plant stage are cluster together row wise.  
Meaning that reseting the index after transformations will destory the signal it contains.

In [9]:
duplicates_df = df_data[df_data.duplicated(keep=False)]

# Display the result (indices are preserved by default)
duplicates_df.head(30)

,System Location Code,Previous Cycle Plant Type,Plant Type,Plant Stage,Temperature Sensor (°C),Humidity Sensor (%),Light Intensity Sensor (lux),CO2 Sensor (ppm),EC Sensor (dS/m),O2 Sensor (ppm),Nutrient N Sensor (ppm),Nutrient P Sensor (ppm),Nutrient K Sensor (ppm),pH Sensor,Water Level Sensor (mm)
7,zoneg,herbs,leafygreens,maturity,20.16,<NA>,317.0,1133,1.52,10,<NA>,<NA>,277,5.8,39.611156
8,zoneg,herbs,leafygreens,maturity,20.16,<NA>,317.0,1133,1.52,10,<NA>,<NA>,277,5.8,39.611156
14,zoneb,herbs,fruitingvegetables,maturity,24.5,<NA>,664.0,1438,2.22,7,238,72,251,6.3,22.530938
15,zoneb,herbs,fruitingvegetables,maturity,24.5,<NA>,664.0,1438,2.22,7,238,72,251,6.3,22.530938
28,zonec,leafygreens,leafygreens,vegetative,21.88,65.62,387.0,1007,0.86,5,115,32,<NA>,6.3,20.0
29,zonec,leafygreens,leafygreens,vegetative,21.88,65.62,387.0,1007,0.86,5,115,32,<NA>,6.3,20.0
36,zoneb,vinecrops,leafygreens,seedling,22.27,<NA>,-105.0,901,1.83,6,93,23,189,6.2,29.0
37,zoneb,vinecrops,leafygreens,seedling,22.27,<NA>,-105.0,901,1.83,6,93,23,189,6.2,29.0
39,zonef,herbs,herbs,vegetative,23.09,<NA>,600.0,1156,1.07,8,238,74,308,6.4,<NA>
40,zonef,herbs,herbs,vegetative,23.09,<NA>,600.0,1156,1.07,8,238,74,308,6.4,<NA>
51,zonef,vinecrops,fruitingvegetables,vegetative,-22.96,<NA>,626.0,1096,1.83,6,<NA>,55,275,6.5,27.0
52,zonef,vinecrops,fruitingvegetables,vegetative,-22.96,<NA>,626.0,1096,1.83,6,<NA>,55,275,6.5,27.0
57,zonec,fruitingvegetables,herbs,maturity,24.0,<NA>,574.0,1251,1.45,5,221,54,261,6.5,21.0
58,zonec,fruitingvegetables,herbs,maturity,24.0,<NA>,574.0,1251,1.45,5,221,54,261,6.5,21.0
61,zonee,vinecrops,fruitingvegetables,seedling,<NA>,<NA>,595.0,1148,2.44,7,123,46,185,6.8,25.0
62,zonee,vinecrops,fruitingvegetables,seedling,<NA>,<NA>,595.0,1148,2.44,7,123,46,185,6.8,25.0
84,zonef,leafygreens,herbs,vegetative,23.72,66.38,483.0,1220,1.7,6,175,66,256,6.1,39.881748
85,zonef,leafygreens,herbs,vegetative,23.72,66.38,483.0,1220,1.7,6,175,66,256,6.1,39.881748
90,zonec,vinecrops,vinecrops,maturity,25.72,75.6,482.0,1083,1.79,9,183,50,200,5.2,14.207275
91,zonec,vinecrops,vinecrops,maturity,25.72,75.6,482.0,1083,1.79,9,183,50,200,5.2,14.207275
95,zonef,vinecrops,fruitingvegetables,vegetative,22.58,<NA>,672.0,1382,0.97,7,179,51,229,6.5,24.0
96,zonef,vinecrops,fruitingvegetables,vegetative,22.58,<NA>,672.0,1382,0.97,7,179,51,229,6.5,24.0
103,zoneg,leafygreens,vinecrops,seedling,<NA>,<NA>,240.0,993,2.39,5,120,30,139,5.6,20.0
104,zoneg,leafygreens,vinecrops,seedling,<NA>,<NA>,240.0,993,2.39,5,120,30,139,5.6,20.0
117,zonef,herbs,fruitingvegetables,seedling,24.99,<NA>,476.0,1021,0.84,7,144,46,157,5.9,<NA>
118,zonef,herbs,fruitingvegetables,seedling,24.99,<NA>,476.0,1021,0.84,7,144,46,157,5.9,<NA>
119,zonee,herbs,leafygreens,seedling,22.63,<NA>,107.0,885,1.16,4,78,23,126,6.0,23.0
120,zonee,herbs,leafygreens,seedling,22.63,<NA>,107.0,885,1.16,4,78,23,126,6.0,23.0
153,zonee,herbs,leafygreens,vegetative,20.45,60.99,228.0,1080,1.99,5,<NA>,33,259,5.4,20.0
154,zonee,herbs,leafygreens,vegetative,20.45,60.99,228.0,1080,1.99,5,<NA>,33,259,5.4,20.0

In [10]:
# Rows seem to be duplicated during entry as the duplicate follows the index of the original.
# Create a flag: True for the 2nd (and 3rd, etc.) occurrence
df_data['is_duplicate'] = df_data.duplicated(keep='first').astype("bool[pyarrow]")

In [11]:
# Remove duplicates
df_data = df_data[df_data['is_duplicate'] == False]

In [12]:
# Verification
df_data.info()

<class 'pandas.DataFrame'>
Index: 50000 entries, 0 to 57488
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   System Location Code          50000 non-null  string
 1   Previous Cycle Plant Type     50000 non-null  string
 2   Plant Type                    50000 non-null  string
 3   Plant Stage                   50000 non-null  string
 4   Temperature Sensor (°C)       42416 non-null  Float64
 5   Humidity Sensor (%)           16214 non-null  Float64
 6   Light Intensity Sensor (lux)  46276 non-null  Float64
 7   CO2 Sensor (ppm)              50000 non-null  Int64
 8   EC Sensor (dS/m)              50000 non-null  Float64
 9   O2 Sensor (ppm)               50000 non-null  Int64
 10  Nutrient N Sensor (ppm)       41328 non-null  string
 11  Nutrient P Sensor (ppm)       45042 non-null  string
 12  Nutrient K Sensor (ppm)       46781 non-null  string
 13  pH Sensor                     50000 non-null  Float64
 14  Water Level Sensor (mm)       42486 non-null  Float64
 15  is_duplicate                  50000 non-null  bool[pyarrow]
dtypes: Float64(6), Int64(2), bool[pyarrow](1), string(7)
memory usage: 8.5 MB

#### Shortening System location code
It would be preferable to shorten them, label encode them to intergers and map them to a lookup table in sql.  
Mainly to reduce the storage size and make it easier to work with in the future

In [13]:
# Removing Zone from `System Location Code` to
df_data['System Location Code'] = df_data['System Location Code'].str[4:]

#### Cleaning non numeric values from Nutirent sensors, casting as Int32
Expecting intergers where i get strings.  
Downcast to Int32 which isnt really necessary now

In [14]:
# Removing non numeric values from nutrient sensors, converting to int
for col in ['Nutrient N Sensor (ppm)', 'Nutrient P Sensor (ppm)', 'Nutrient K Sensor (ppm)']:
    df_data[col] = (
        df_data[col]
        .astype(str)                                  # ensure string
        .str.extract(r'(\d+)')                        # keep only digits
        .replace(['none', 'nan', 'null', ''], np.nan) # unify nulls
        .astype('Int32')                              # nullable int dtype
    )

In [15]:
# Examining counts

In [16]:
df_data['Plant Stage'].value_counts(dropna=False, ascending=True)

Plant Stage
maturity      16538
vegetative    16608
seedling      16854
Name: count, dtype: int64[pyarrow]

In [17]:
df_data['System Location Code'].value_counts()

System Location Code
c    7218
g    7206
e    7204
b    7200
a    7075
f    7071
d    7026
Name: count, dtype: int64[pyarrow]

Does not seem to be an ordinal flow to the zones, but a definate order to plant stage

In [18]:
df_data['Plant Type'].value_counts(dropna=False, ascending=True)

Plant Type
vinecrops             12411
leafygreens           12502
herbs                 12528
fruitingvegetables    12559
Name: count, dtype: int64[pyarrow]

In [19]:
df_data['Previous Cycle Plant Type'].value_counts(dropna=False, ascending=True)

Previous Cycle Plant Type
herbs                 12381
vinecrops             12459
leafygreens           12568
fruitingvegetables    12592
Name: count, dtype: int64[pyarrow]

#### New label `No rotation`

In [20]:
(df_data['Previous Cycle Plant Type'] == df_data['Plant Type']).value_counts()

False    37479
True     12521
Name: count, dtype: int64[pyarrow]

No rotation might possibly be a feature

In [21]:
df_data['No Rotation'] = df_data['Previous Cycle Plant Type'] == df_data['Plant Type']

In [22]:
df_data.info()

<class 'pandas.DataFrame'>
Index: 50000 entries, 0 to 57488
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   System Location Code          50000 non-null  string
 1   Previous Cycle Plant Type     50000 non-null  string
 2   Plant Type                    50000 non-null  string
 3   Plant Stage                   50000 non-null  string
 4   Temperature Sensor (°C)       42416 non-null  Float64
 5   Humidity Sensor (%)           16214 non-null  Float64
 6   Light Intensity Sensor (lux)  46276 non-null  Float64
 7   CO2 Sensor (ppm)              50000 non-null  Int64
 8   EC Sensor (dS/m)              50000 non-null  Float64
 9   O2 Sensor (ppm)               50000 non-null  Int64
 10  Nutrient N Sensor (ppm)       41328 non-null  Int32
 11  Nutrient P Sensor (ppm)       45042 non-null  Int32
 12  Nutrient K Sensor (ppm)       46781 non-null  Int32
 13  pH Sensor                     50000 non-null  Float64
 14  Water Level Sensor (mm)       42486 non-null  Float64
 15  is_duplicate                  50000 non-null  bool[pyarrow]
 16  No Rotation                   50000 non-null  bool[pyarrow]
dtypes: Float64(6), Int32(3), Int64(2), bool[pyarrow](2), string(4)
memory usage: 7.6 MB